app_profile/urls.py
# testing
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^(?P<username>\w+)/$', index, name='profile_page'),
]

app_timeline/urls.py
from django.conf.urls import url
from .views import (
    index, add_status, delete_status, comment_status, index_comment)

urlpatterns = [
    url(r'^(?P<username>\w+)/timeline/$', index, name='timeline_page'),
    url(r'^(?P<username>\w+)/timeline/add_status/$', add_status, name='add_status'),
    url(r'^(?P<username>\w+)/timeline/delete/(?P<status_id>[0-9]+)/$', delete_status, name='delete_status'),
    url(r'^(?P<username>\w+)/timeline/comment/(?P<status_id>[0-9]+)/$', index_comment, name='comment'),
    url(r'^(?P<username>\w+)/timeline/comment/(?P<status_id>[0-9]+)/post_comment/$', comment_status, name='comment_status'),
]

ling_in/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
import app_timeline.urls as app_timeline
import app_profile.urls as app_profile
import app_home.urls as app_home
import app_dashboard.urls as app_dashboard
import app_friend.urls as app_friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(app_home, namespace='app_home')),
    url(r'^', include(app_timeline, namespace='app_timeline')),
    url(r'^', include(app_dashboard, namespace='app_dashboard')),
    url(r'^', include(app_friend, namespace='app_friend')),
    url(r'^', include(app_profile, namespace='app_profile')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_timeline/models.py
from django.db import models
from app_profile.models import UserProfile

# Create your models here.

class Status(models.Model):
    """
    Description:

    """
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    content = models.CharField(max_length=350, blank=False, null=False)
    likes = models.PositiveIntegerField(default=0, blank=True, editable=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return "%s\n%s" % (self.user.username, self.content)

    class Meta:
        ordering = ('created_at', 'updated_at')


class Comment(models.Model):
    """
    Description:
    """
    # relation
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)

    content = models.CharField(max_length=350, blank=False, null=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return "%s: %s - %s" % (self.status, self.user.username, self.content)

    class Meta:
        ordering = ('created_at', 'updated_at')

app_timeline/forms.py
from django import forms
from .models import Status, Comment

# Form

class StatusPostForm(forms.Form):
    """
    Description:
    Form to input status from user

    """
    error_message = {
        'required':'This field is required'
    }

    status_attrs = {
        'type':'text',
        'class':'status-form-textarea',
        'placeholder':'What do you think?',
        'id':'status-form-textarea',
        'max-length':350,
        'cols': 100,
        'rows': 4,
        'onkeydown': 'calculateChar()',
        'onpaste': 'calculateChar()',
    }

    content = forms.CharField(label='',
                              max_length=350,
                              required=True,
                              widget=forms.Textarea(attrs=status_attrs))

    class Meta:
        model = Status


class CommentForm(forms.Form):
    """
    Description:
    Form for input comment to the status from user
    """
    error_message = {
        'required':'This field is required'
    }

    status_attrs = {
        'type':'text',
        'class':'status-form-textarea',
        'placeholder':'What do you think?',
        'id':'status-form-textarea',
        'max-length':200,
        'cols': 100,
        'rows': 4,
        'onkeydown': 'calculateChar()',
        'onpaste': 'calculateChar()',
    }

    # username = forms.CharField(label='',
    #                           max_length=128,
    #                           required=True,
    #                           widget=forms.Textarea(attrs=status_attrs))

    content = forms.CharField(label='',
                              max_length=350,
                              required=True,
                              widget=forms.Textarea(attrs=status_attrs))

    class Meta:
        model = Comment

app_timeline/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from ling_in import strings
from .models import Status, Comment
from app_profile.models import UserProfile
from .forms import StatusPostForm, CommentForm

# Create your views here.

response = {
    'TITLE': strings.TITLE,
    'YEAR': strings.YEAR,
}

class StatusComment:
    """
    without dictionary
    Status is an object and comment must be an iterable object like list or tuple
    """
    def __init__(self, status, comment=list()):
        self.status = status
        self.comment = comment
    
    def __str__(self):
        return "%s: %d" % (self.status, len(self.comment))
    
    def __repr__(self):
        return "%s: %d" % (self.status, len(self.comment))

def index(request, username=None):
    """

    :param request:
    :param username:
    :return:
    """
    model = Status
    template_name = 'app_timeline/index_timeline.html'
    user = get_object_or_404(UserProfile, username=username)

    # get context
    response['user'] = user
    response['status_form'] = StatusPostForm
    response['page_title'] = 'Timeline'

    status_post = get_queryset(user)
    page = request.GET.get('page', 1)
    
    paginator = Paginator(status_post, 10)

    no_post = True
    if(len(status_post) < 11):
        no_post = False
    
    status_stream = paginator.page(page)

    response['no_post'] = no_post
    response['status_stream'] = status_stream
    return render(request, template_name, response)


def get_queryset(user):
    """

    :param user:
    :return:
    """
    model = Status
    status_by_user = model.objects.all().order_by('-created_at') #for now we grab all status

    if(len(status_by_user) > 50):
        status_by_user = status_by_user[:50]

    status_with_comment = []
    ## this is bad ##
    for st in status_by_user:
        comment_for_this_st = Comment.objects.filter(status=st).order_by('-created_at')

        if(len(comment_for_this_st) > 10):
            comment_for_this_st = comment_for_this_st[:10]

        status_with_comment.append(
            StatusComment(
                status=st, 
                comment=comment_for_this_st
            )
        )

    return status_with_comment


def add_status(request, username=None):
    """
    create new status based on user request
    :param request:
    :param username:
    :return:
    """
    # get username
    model = Status
    user = get_object_or_404(UserProfile, username=username)
    form = StatusPostForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        content = request.POST['content']
        # create status
        model(user=user, content=content).save()
        # messages.success(request, "Success")

        return HttpResponseRedirect('/%s/timeline/' % (username))

    else:
        return HttpResponseRedirect('/%s/timeline/' % (username))


def delete_status(request, username=None, status_id=None):
    """
    @TODO need to find the safe method to delete object
    :param request:
    :param username:
    :param status_id:
    :return:
    """
    model = Status

    user = get_object_or_404(UserProfile, username=username)
    get_object_or_404(model, pk=status_id).delete()
    return HttpResponseRedirect('/%s/timeline/' % (user.username))

def index_comment(request, username=None, status_id=None):
    
    user = get_object_or_404(UserProfile, username=username)
    status = get_object_or_404(Status, pk=status_id)

    response['page_title'] = 'Comment'
    response['user'] = user
    response['status'] = status
    response['comment_form'] = CommentForm
    template_name = 'app_timeline/index_timeline_comment.html'
    return render(request, template_name, response)

def comment_status(request, username=None, status_id=None):
    # get commentator and status that commented by commentator
    user_commentator = get_object_or_404(UserProfile, username=username)
    status_commented = get_object_or_404(Status, pk=status_id)

    model = Comment
    form = CommentForm(request.POST or None)

    if(request.method == 'POST' and form.is_valid()):
        content = request.POST['content']
        # create comment
        model(user=user_commentator, status=status_commented, content=content).save()
        # messages.success(request, "Success")

        return HttpResponseRedirect('/%s/timeline/' % (username))

    else:
        return HttpResponseRedirect('/%s/timeline/' % (username))

app_timeline/templates/app_timeline/index_timeline.html
{% extends "app_home/layout/base.html" %}
{% load static %}
{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/timeline.css' %}" />
{% endblock %}
{% block content %}
<section class="input-section" id="input-section">
    <div class="container" onscroll="minimizeStatusForm()">
        <div class="flex">
            <form class="form" id="form" method="POST" action="{% url 'app_timeline:add_status' user.username %}"
            onclick="growStatusForm()">
                {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                            <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-sm-1">
                        {% if user.photo %}
                        <img id="img" src="{{ user.photo.url }}">
                        {% else %}
                        <img class="img" src="{% static 'img/profile_pic.svg' %}">
                        {% endif %}
                    </div>
                    <div class="col-sm-11">
                        {% csrf_token %}
                        {{ status_form }}                        
                    </div>
                </div>
                <div class="pull-right submit-button">
                    <span id="cal_char">350</span>
                    <input id="submit" type="submit" class="btn btn-lg btn-info" value="Post">
                </div>
                <br>
            </form>
        </div>
    </div>
</section>
<section class="status-stream" id="status-stream">
    <div class="container">
        <div class="flex">
            <div class="stream">
            {% include "app_timeline/timeline_stream.html" %}
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block script %}
<script type="application/javascript">
    const minSc = window.matchMedia( "(min-width: 768px)");
    var clicked = false;
    function growStatusForm() {
        clicked = true;
        $('#input-section form').css('height','auto');$('#input-section form .submit-button').css('display','block');
        $('#input-section form .status-form-textarea').animate({'max-height':'100%','border-radius':'1rem'});
        if(minSc.matches){$('#input-section form img').css({'max-width':'75px', 'max-height':'75px'})}
    }

    $(document).scroll(function minimizeStatusForm(){
        if($(this).scrollTop() > 100){
            $('#input-section form').css('height', '100px');
            $('#input-section form .submit-button').css('display', 'none');
            $('#input-section form .status-form-textarea').css({'max-height':'50px', 'border-radius':'2rem'});
            if(minSc.matches){
            $('#input-section form img').css({'max-width':'50px','max-height':'50px'});
            }
        } //else if (clicked) {
        //     growStatusForm()
        // }
    })

    function calculateChar() {
        var input_form = document.getElementById('status-form-textarea').value;
        var value_length = input_form.length + 1;
        document.getElementById('cal_char').innerHTML = 351 - value_length;
    }
</script>
{% endblock %}

app_timeline/templates/app_timeline/index_timeline_comment.html
{% extends "app_home/layout/base.html" %}
{% load static %}
{% load markdown_deux_tags %}
{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/timeline.css' %}" />
{% endblock %}
{% block content %}
<section class="input-section" id="input-section">
    <div class="container" onscroll="minimizeStatusForm()">
        <div class="flex">
            <div class="status-stream" id="status-stream">
                <div class="stream">
                    <div class="status-hover">
                        <div class="status" id="{{ status.id }}">
                            <div class="header">
                                <div>
                                    {% if status.user.photo %}
                                    <img class="display-pic" src="{{ status.user.photo.url }}">
                                    {% else %}
                                    <img class="display-pic" src="{% static 'img/profile_pic.svg' %}">
                                    {% endif %}
                                </div>
                                <div>
                                    <!-- link to profile -->
                                    <a href="{% url 'app_profile:profile_page' status.user.username %}" >
                                        <h4 class="card-title">@{{ status.user.username }}</h4>
                                    </a>
                                </div>
                            </div>
                            <p>{{ status.content|markdown }}</p>
                            <p class="status-date">{{status.created_at}}<p/>
                            {% if status.user == user %}
                            <div class="pull-right">
                                <a id="status-{{ status.id }}" href="{% url 'app_timeline:delete_status' status.user.username status.id %}" >
                                    <img class="delete-button" src="{% static 'img/delete.svg' %}">
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <form id="form" method="POST" action="{% url 'app_timeline:comment_status' user.username status.id %}"
            onclick="growStatusForm()">
                {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                            <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-sm-1">
                        {% if user.photo %}
                        <img id="img" src="{{ user.photo.url }}">
                        {% else %}
                        <img class="img" src="{% static 'img/profile_pic.svg' %}">
                        {% endif %}
                    </div>
                    <div class="col-sm-11">
                        {% csrf_token %}
                        {{ comment_form }}                        
                    </div>
                </div>
                <div class="pull-right submit-button">
                    <span id="cal_char">350</span>
                    <input id="submit" type="submit" class="btn btn-lg btn-info" value="Post">
                </div>
                <br>
            </form>
        </div>
    </div>
</section>
{% endblock %}
{% block script %}
<script type="application/javascript">
    const minSc = window.matchMedia( "(min-width: 768px)");
    var clicked = false;
    function growStatusForm() {
        clicked = true;
        $('#input-section form').css('height','auto');$('#input-section form .submit-button').css('display','block');
        $('#input-section form .status-form-textarea').animate({'max-height':'100%','border-radius':'1rem'});
        if(minSc.matches){$('#input-section form img').css({'max-width':'75px', 'max-height':'75px'})}
    }
    $(document).scroll(function minimizeStatusForm(){
        if($(this).scrollTop() > 100){
            $('#input-section form').css('height', '100px');
            $('#input-section form .submit-button').css('display', 'none');
            $('#input-section form .status-form-textarea').css({'max-height':'50px', 'border-radius':'2rem'});
            if(minSc.matches){
            $('#input-section form img').css({'max-width':'50px','max-height':'50px'});
            }
        } //else if (clicked) {
        //     growStatusForm()
        // }
    })

    function calculateChar() {
        var input_form = document.getElementById('status-form-textarea').value;
        var value_length = input_form.length + 1;
        document.getElementById('cal_char').innerHTML = 351 - value_length;
    }  
</script>
{% endblock %}

app_timeline/templates/app_timeline/timeline_stream.html
{% load static %}
{% load markdown_deux_tags %}
<div class="infinite-container">
        <div class="flex-item">
            {% if status_stream %}
            {% for data in status_stream %}
            <!-- status -->
            <div class="status-hover">
                <div class="status" id="{{ data.id }}">
                    <div class="header">
                        <div>
                            {% if data.status.user.photo %}
                            <img class="display-pic" src="{{ data.status.user.photo.url }}">
                            {% else %}
                            <img class="display-pic" src="{% static 'img/profile_pic.svg' %}">
                            {% endif %}
                        </div>
                        <div>
                            <!-- link to profile -->
                            <a href="{% url 'app_profile:profile_page' data.status.user.username %}" >
                                <h4 class="card-title">@{{ data.status.user.username }}</h4>
                            </a>
                        </div>
                    </div>
                    <p>{{ data.status.content|markdown }}</p>
                    <p class="status-date">{{data.status.created_at}}<p/>
                    {% if data.status.user == user %}
                    <div class="pull-right">
                        <a id="data-{{ data.status.id }}" href="{% url 'app_timeline:delete_status' data.status.user.username data.status.id %}" >
                            <img class="delete-button" src="{% static 'img/delete.svg' %}">
                        </a>
                    </div>
                    {% endif %}
                    <div class="pull-right">
                        <a id="data-{{ data.status.id }}" href="{% url 'app_timeline:comment' user.username data.status.id %}" >
                            <img class="delete-button" src="{% static 'img/comment.svg' %}">
                        </a>
                    </div>
                </div>
            </div>
            {% for comment in data.comment %}
            <div class="comment-hover">
                <div class="comment" id="{{ comment.id }}">
                    <div class="header">
                        <div>
                            {% if comment.user.photo %}
                            <img class="display-pic" src="{{ comment.user.photo.url }}">
                            {% else %}
                            <img class="display-pic" src="{% static 'img/profile_pic.svg' %}">
                            {% endif %}
                        </div>
                        <div>
                            <!-- link to profile -->
                            <a href="{% url 'app_profile:profile_page' comment.user.username %}" >
                                <h4 class="card-title">@{{ comment.user.username }}</h4>
                            </a>
                        </div>
                    </div>
                    <p>{{ comment.content|markdown }}</p>
                    <p class="status-date">{{ comment.created_at }}<p/>
                </div>
            </div>
            {% endfor %}
            {% endfor %}
            {% else %}
            <div class="status-hover">
                <div class="status">
                    <h4>Hey, let's create your first post!</h4>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
{% if no_post %}
<div class="container">
    <div class="flex">
        <div class="flex-item">
            <div class="refresh">
                {% if status_stream.has_next %}
                <a class="infinite-more-link" href="?page={{ status_stream.next_page_number }}">More</a>
                {% else %}
                <a class="infinite-more-link" href="?page={{ status_stream.previous_page_number }}">Back</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endif %}