app_home/urls.py
from django.conf.urls import url
from .views import index, login_account, signup_account, create_account

urlpatterns = [
    url(r'^$', index, name='homepage'),
    url(r'^account/$', signup_account, name='account'),
    url(r'^account/login/$', login_account, name='account_login'),
    url(r'^account/signup/$', create_account, name='account_signup'),
]

ling_in/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
import app_timeline.urls as app_timeline
import app_profile.urls as app_profile
import app_home.urls as app_home
import app_dashboard.urls as app_dashboard
import app_friend.urls as app_friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(app_home, namespace='app_home')),
    url(r'^', include(app_timeline, namespace='app_timeline')),
    url(r'^', include(app_dashboard, namespace='app_dashboard')),
    url(r'^', include(app_friend, namespace='app_friend')),
    url(r'^', include(app_profile, namespace='app_profile')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_home/models.py
from django.db import models

# Create your models here.

app_home/forms.py
from django import forms
from app_profile.models import UserProfile

# Form

class LoginForm(forms.Form):
    """
    Description:
    Form to input username

    """
    error_message = {
        'required':'This field is required'
    }

    status_attrs = {
        'type':'text',
        'class':'login-form-input',
        'placeholder':'What is your username?',
        'cols': 100,
        'rows': 1,
    }

    username = forms.CharField(label='',
                              required=True,
                              widget=forms.TextInput(attrs=status_attrs))

class SignUpForm(forms.Form):
    """
    Description:
    Form to create username
    """
    error_message = {
        'required':'This field is required'
    }

    input_attrs = {
        'type':'text',
        'class':'signup-form-input',
        'placeholder':'',
        'cols': 50,
        'rows': 1,
    }

    date_attrs = {
        'type':'datetime-local',
        'name':'date',
        'id':'date',
        'class':'signup-form-input',
    }

    photo_attrs = {
        'class':'signup-form-input',
    }

    username = forms.CharField(label='Username*',
                               required=True,
                               widget=forms.TextInput(attrs=input_attrs))
    
    photo = forms.ImageField(label='Photo',
                            required=False,
                            widget=forms.ClearableFileInput(photo_attrs))

    first_name = forms.CharField(label='First Name*',
                                 required=True,
                                 widget=forms.TextInput(attrs=input_attrs))

    middle_name = forms.CharField(label='Middle Name',
                                  required=False,
                                  widget=forms.TextInput(attrs=input_attrs))

    last_name = forms.CharField(label='Last Name*',
                                required=True,
                                widget=forms.TextInput(attrs=input_attrs))

    email = forms.EmailField(label='Email*',
                            required=True,
                            widget=forms.EmailInput(attrs=input_attrs))

    gender = forms.ChoiceField(label='Gender*',
                             required=True,
                             choices=UserProfile.GENDER_CHOICE,
                             widget=forms.Select(input_attrs))

    class Meta:
        model = UserProfile

app_home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from ling_in.strings import TITLE, YEAR
from .forms import LoginForm, SignUpForm
from app_profile.models import UserProfile
from datetime import datetime

# Create your views here.
response = {
    'TITLE':TITLE,
    'YEAR':YEAR,
}

def index(request):
    template_name = 'app_home/index_login.html'

    response['page_title'] = 'Home'
    response['login_form'] = LoginForm
    response['message'] = 'Username'

    return render(request, template_name, response)


def signup_account(request):
    template_name = 'app_home/index_account.html'

    response['page_title'] = 'Home / Sign up'
    response['signup_form'] = SignUpForm
    response['message'] = 'Create Account'

    return render(request, template_name, response)


def login_account(request):
    model = UserProfile
    form = LoginForm(request.POST or None)

    if(request.method == 'POST' and form.is_valid()):
        username = request.POST['username'].strip()
        # because username is unique so we just use filter
        search = UserProfile.objects.filter(username=username)

        if(len(search) != 1):
            messages.error(request, 'Username does not exist')
            return HttpResponseRedirect('/')

        user = search[0]
        return HttpResponseRedirect('/%s/timeline/' % (user.username))

    else:
        return HttpResponseRedirect('/')


def create_account(request):
    model = UserProfile
    form = SignUpForm(request.POST or None, request.FILES)

    if (request.method == 'POST' and form.is_valid()):
        username = request.POST['username'].strip()
        # because username is unique so we just use filter
        search = UserProfile.objects.filter(username=username)

        if (len(search) > 0):
            messages.error(request, 'Username not available')
            return HttpResponseRedirect('/account/')

        response = request.POST

        user = model(
            username=username,
            first_name=response['first_name'].strip(),
            middle_name=response['middle_name'].strip(),
            last_name=response['last_name'].strip(),
            email=response['email'].strip(),
            gender=response['gender'],
            birth_date=response['date']
        )
        user.photo = form.cleaned_data['photo']
        user.save()

        return HttpResponseRedirect('/%s/timeline/' % (user.username))

    else:
        return HttpResponseRedirect('/account/')

app_home/templates/app_home/index_account.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {% include "app_home/partials/head.html" %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/homepage.css' %}" />
</head>
<body>
    <content>
        <div class="container">
            <div class="flex">
                <div id="signup-section" class="signup-section">
                    <h1 class="font-weight-bold font-italic text-center">{{ TITLE }}</h1><br>
                    <h3 class="font-weight-bold text-center">{{ message }}</h3>
                    <br>
                    <form id="form" method="POST" enctype="multipart/form-data" action="{% url 'app_home:account_signup' %}">
                        {% if messages %}
                            <div class="messages">
                                {% for message in messages %}
                                    <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                        {% csrf_token %}
                        {% for field in signup_form  %}
                        <div class="flex-item">
                            <b>{{ field.label_tag }}</b>
                            <br>
                            {{ field }}
                            <br>
                            <br>
                        </div>
                        {% endfor %}
                        <div class="flex-item">
                            <b>Birth Dates</b>
                            <br>
                            <input class="signup-form-date" type="date" name="date" id="date" required="required"/>
                            <br>
                            <br>    
                        </div>
                        <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Create">
                        <br>
                    </form>
                </div>
            </div>
        </div>
    </content>
</body>
</html>

app_home/templates/app_home/index_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    {% include "app_home/partials/head.html" %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/homepage.css' %}" />
</head>
<body>
    <content>
        <div class="flex-center">
            <div class="flex-item" id="login-section">
                <h1 class="font-weight-bold font-italic text-center">{{ TITLE }}</h1><br>
                <!-- <h3 class="font-weight-bold text-center">{{ message }}</h3> -->
                <br>
                <form id="form" method="POST" action="{% url 'app_home:account_login' %}">
                    {% if messages %}
                    <div class="messages">
                        {% for message in messages %}
                        <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                        {% endfor %}
                    </div>
                    {% endif %}
                    {% csrf_token %}
                    {{ login_form }}    
                    <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Go">          
                    </div>
                </form>
                <br>
                <!-- sign up page -->
                <a class="" href="{% url 'app_home:account' %}">Sign up?</a>
            </div>
        </div>
    </content>
</body>
</html>