app_dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^(?P<username>\w+)/stats/$', index, name='stats'),
]

app_friend/urls.py
from django.conf.urls import url
from .views import index, new_friend, delete_friend


urlpatterns = [
    url(r'^(?P<username>\w+)/friends/$', index, name='index'),
    url(r'^(?P<username>\w+)/friends/add_friend/$', new_friend, name='add_friend'),
    url(r'^(?P<username>\w+)/friends/delete_friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete_friend')
 ]

app_home/urls.py
from django.conf.urls import url
from .views import index, login_account, signup_account, create_account

urlpatterns = [
    url(r'^$', index, name='homepage'),
    url(r'^account/$', signup_account, name='account'),
    url(r'^account/login/$', login_account, name='account_login'),
    url(r'^account/signup/$', create_account, name='account_signup'),
]

app_profile/urls.py
# testing
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^(?P<username>\w+)/$', index, name='profile_page'),
]

app_timeline/urls.py
from django.conf.urls import url
from .views import (
    index, add_status, delete_status, comment_status, index_comment)

urlpatterns = [
    url(r'^(?P<username>\w+)/timeline/$', index, name='timeline_page'),
    url(r'^(?P<username>\w+)/timeline/add_status/$', add_status, name='add_status'),
    url(r'^(?P<username>\w+)/timeline/delete/(?P<status_id>[0-9]+)/$', delete_status, name='delete_status'),
    url(r'^(?P<username>\w+)/timeline/comment/(?P<status_id>[0-9]+)/$', index_comment, name='comment'),
    url(r'^(?P<username>\w+)/timeline/comment/(?P<status_id>[0-9]+)/post_comment/$', comment_status, name='comment_status'),
]

ling_in/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
import app_timeline.urls as app_timeline
import app_profile.urls as app_profile
import app_home.urls as app_home
import app_dashboard.urls as app_dashboard
import app_friend.urls as app_friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(app_home, namespace='app_home')),
    url(r'^', include(app_timeline, namespace='app_timeline')),
    url(r'^', include(app_dashboard, namespace='app_dashboard')),
    url(r'^', include(app_friend, namespace='app_friend')),
    url(r'^', include(app_profile, namespace='app_profile')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_home/models.py
from django.db import models

# Create your models here.

app_home/forms.py
from django import forms
from app_profile.models import UserProfile

# Form

class LoginForm(forms.Form):
    """
    Description:
    Form to input username

    """
    error_message = {
        'required':'This field is required'
    }

    status_attrs = {
        'type':'text',
        'class':'login-form-input',
        'placeholder':'What is your username?',
        'cols': 100,
        'rows': 1,
    }

    username = forms.CharField(label='',
                              required=True,
                              widget=forms.TextInput(attrs=status_attrs))

class SignUpForm(forms.Form):
    """
    Description:
    Form to create username
    """
    error_message = {
        'required':'This field is required'
    }

    input_attrs = {
        'type':'text',
        'class':'signup-form-input',
        'placeholder':'',
        'cols': 50,
        'rows': 1,
    }

    date_attrs = {
        'type':'datetime-local',
        'name':'date',
        'id':'date',
        'class':'signup-form-input',
    }

    photo_attrs = {
        'class':'signup-form-input',
    }

    username = forms.CharField(label='Username*',
                               required=True,
                               widget=forms.TextInput(attrs=input_attrs))
    
    photo = forms.ImageField(label='Photo',
                            required=False,
                            widget=forms.ClearableFileInput(photo_attrs))

    first_name = forms.CharField(label='First Name*',
                                 required=True,
                                 widget=forms.TextInput(attrs=input_attrs))

    middle_name = forms.CharField(label='Middle Name',
                                  required=False,
                                  widget=forms.TextInput(attrs=input_attrs))

    last_name = forms.CharField(label='Last Name*',
                                required=True,
                                widget=forms.TextInput(attrs=input_attrs))

    email = forms.EmailField(label='Email*',
                            required=True,
                            widget=forms.EmailInput(attrs=input_attrs))

    gender = forms.ChoiceField(label='Gender*',
                             required=True,
                             choices=UserProfile.GENDER_CHOICE,
                             widget=forms.Select(input_attrs))

    class Meta:
        model = UserProfile

app_home/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from ling_in.strings import TITLE, YEAR
from .forms import LoginForm, SignUpForm
from app_profile.models import UserProfile
from datetime import datetime

# Create your views here.
response = {
    'TITLE':TITLE,
    'YEAR':YEAR,
}

def index(request):
    template_name = 'app_home/index_login.html'

    response['page_title'] = 'Home'
    response['login_form'] = LoginForm
    response['message'] = 'Username'

    return render(request, template_name, response)


def signup_account(request):
    template_name = 'app_home/index_account.html'

    response['page_title'] = 'Home / Sign up'
    response['signup_form'] = SignUpForm
    response['message'] = 'Create Account'

    return render(request, template_name, response)


def login_account(request):
    model = UserProfile
    form = LoginForm(request.POST or None)

    if(request.method == 'POST' and form.is_valid()):
        username = request.POST['username'].strip()
        # because username is unique so we just use filter
        search = UserProfile.objects.filter(username=username)

        if(len(search) != 1):
            messages.error(request, 'Username does not exist')
            return HttpResponseRedirect('/')

        user = search[0]
        return HttpResponseRedirect('/%s/timeline/' % (user.username))

    else:
        return HttpResponseRedirect('/')


def create_account(request):
    model = UserProfile
    form = SignUpForm(request.POST or None, request.FILES)

    if (request.method == 'POST' and form.is_valid()):
        username = request.POST['username'].strip()
        # because username is unique so we just use filter
        search = UserProfile.objects.filter(username=username)

        if (len(search) > 0):
            messages.error(request, 'Username not available')
            return HttpResponseRedirect('/account/')

        response = request.POST

        user = model(
            username=username,
            first_name=response['first_name'].strip(),
            middle_name=response['middle_name'].strip(),
            last_name=response['last_name'].strip(),
            email=response['email'].strip(),
            gender=response['gender'],
            birth_date=response['date']
        )
        user.photo = form.cleaned_data['photo']
        user.save()

        return HttpResponseRedirect('/%s/timeline/' % (user.username))

    else:
        return HttpResponseRedirect('/account/')

app_home/templates/app_home/partials/footer.html
<p>Copyright &copy; {{ YEAR }} {{ TITLE }}</p>

app_home/templates/app_home/partials/head.html
    {% load staticfiles %}
    {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">    
        <link rel="shortcut icon" href="https://cdn1.iconfinder.com/data/icons/web-3/512/link-128.png" />
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lobster+Two" rel="stylesheet">
        <title>
            {% block title %} {{ TITLE }} / {{ page_title }} {% endblock %}
        </title>

app_home/templates/app_home/partials/header.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
      <div class="navbar-brand">
        <div class="flex-item">
          <a href="/">
            <img class="logo" src="https://cdn1.iconfinder.com/data/icons/web-3/512/link-128.png">
            
          </a>
        </div>
      </div>
      <div id="sidenav" class="sidenav">
          <a href="{% url 'app_dashboard:stats' user.username %}">Dashboard</a>
          <a href="{% url 'app_timeline:timeline_page' user.username %}">Timeline</a>
          <a href="{% url 'app_profile:profile_page' user.username %}">Profile</a>
          <a href="{% url 'app_friend:index' user.username %}">Friends</a>
          <a href="{% url 'app_home:homepage' %}" class="button-buttom">Sign out</a>
          <a href="javascript:void(0)" id="close" onclick="closeNav()">&times; Close</a>
        </div>
      <div class="pull-right">
      <span id="button-header" class="flex-item" onclick="openNav()">
          {% if user.photo %}
          <img class="display-pic" src="{{ user.photo.url }}">&#9776;
          {% else %}
          <img class="display-pic" src="{% static 'img/profile_pic.svg' %}">&#9776;
          {% endif %}
      </span>
    </div>
  </div>
</nav>