app_friend/urls.py
from django.conf.urls import url
from .views import index, new_friend, delete_friend


urlpatterns = [
    url(r'^(?P<username>\w+)/friends/$', index, name='index'),
    url(r'^(?P<username>\w+)/friends/add_friend/$', new_friend, name='add_friend'),
    url(r'^(?P<username>\w+)/friends/delete_friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete_friend')
 ]

ling_in/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static
import app_timeline.urls as app_timeline
import app_profile.urls as app_profile
import app_home.urls as app_home
import app_dashboard.urls as app_dashboard
import app_friend.urls as app_friend

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(app_home, namespace='app_home')),
    url(r'^', include(app_timeline, namespace='app_timeline')),
    url(r'^', include(app_dashboard, namespace='app_dashboard')),
    url(r'^', include(app_friend, namespace='app_friend')),
    url(r'^', include(app_profile, namespace='app_profile')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_friend/models.py
from django.db import models
from app_profile.models import UserProfile

class Friend(models.Model):
    name = models.CharField(max_length=100)
    url = models.URLField(unique=True)

    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    
    def __str__(self):
        return "%s - %s" % (
            self.name,
            self.url
        )

class Friendship(models.Model):
    friend = models.ForeignKey(Friend, models.CASCADE)
    user = models.ForeignKey(UserProfile, models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return "%s - %s" % (
            self.user.username,
            self.friend.name
        )

app_friend/forms.py
from django import forms

class FriendForm(forms.Form):
    error_message = {
        'required':'This field is required'
    }

    input_attrs = {
        'type':'text',
        'class':'input-form-name',
        'id':'input-form-name',
        'placeholder':'Who is your friend?',
        'cols': 50,
        'rows': 1,
    }

    url_attrs = {
        'type':'text',
        'class':'input-form-name',
        'id':'input-form-url',
        'placeholder':'What is your friend\'s url',
        'cols': 50,
        'rows': 1,
    }


    name = forms.CharField(label='Nama', required=True,
                           widget=forms.TextInput(attrs=input_attrs),
                           error_messages=error_message)

    url = forms.URLField(label='URL',required=True,
                         widget=forms.URLInput(attrs=url_attrs),
                         error_messages=error_message,
                         initial='https://')
    

app_friend/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
import requests
from .models import Friendship,Friend
from app_profile.models import UserProfile
from .forms import FriendForm
import requests
from ling_in import strings

response = {
    'TITLE':strings.TITLE,
    'YEAR':strings.YEAR,
}

# Create your views here.
def index(request, username=None):
    html = 'app_friend/add_friend.html'
    user=get_object_or_404(UserProfile,username=username)
    
    response['page_title'] = 'Friends'
    response['friends'] = get_query_friends(user)
    response['friend_form'] = FriendForm
    response['user'] = user
    return render(request, html, response)

def get_query_friends(user):
    friendship = Friendship.objects.filter(user=user)
    friends = []

    for f in friendship:
        friends.append(f.friend)

    return friends

def validate_url(url=str()):
    try:
        resp = requests.get(url)
        if(resp.status_code < 400):
            return True
    except requests.exceptions.MissingSchema:
        # the uxrl is not valid --> regex
        return False

    return False

def new_friend(request, username=None):

    user=get_object_or_404(UserProfile, username=username)

    form = FriendForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        friend_name = request.POST['name']
        friend_url = request.POST['url']

        url_valid = validate_url(friend_url)

        if(url_valid):
            # if url is valid, then create the relation
            get_friend = Friend.objects.filter(url=friend_url)
            
            # check if friend is already in database
            if(len(get_friend) > 0):
                friend = get_friend[0]
            else:
                friend=Friend(name=friend_name, url=friend_url)
                friend.save()

            # check if the relation between user and friend is already created in the past
            # if true, then we won't make it.

            # get friendship that has relation with user and the friend
            # get_friendship = Friendship.objects.filter(user=user, friend=friend)

            Friendship(user=user, friend=friend).save()

        return HttpResponseRedirect('/%s/friends/' % (username))
    else:
        return HttpResponseRedirect('/%s/friends/' % (username))

def delete_friend(request, username=None, friend_id=None):
    """
    @TODO need to find the safe method to delete object
    :param request:
    :param username:
    :param status_id:
    :return:
    """
    model = Friend

    user = get_object_or_404(UserProfile, username=username)
    get_object_or_404(model, pk=friend_id).delete()
    return HttpResponseRedirect('/%s/friends/' % (user.username))

app_friend/templates/app_friend/add_friend.html
{% extends "app_home/layout/base.html" %}
{% load static %}
{% block stylesheet %}
<link rel="stylesheet" type="text/css" href="{% static 'css/app_friend.css' %}" />
{% endblock %}
{% block content %}
<hr/>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'app_friend:add_friend' user.username %}">
            <h2>Add Your Friend</h2>
            {% csrf_token %}
            {{ friend_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="subtitle">My Friend</h2>
        <div class="flex">
            {% if friends %}
                {% for data in friends %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div>
                                <img class="profile-friends" src="{% static 'img/profile_pic.svg' %}">
                            </div>
                            <div class="to-do-list-title">
                                {{data.name}}
                            </div>
                            <div class="to-do-list-date-added">
                                {{data.created_at}}
                            </div>
                            <div class="to-do-list-description">
                                <a href= "{{data.url }}" >{{data.url }}</a>
                            </div>
                            <div class="to-do-list-delete">
                                <a href="{% url 'app_friend:delete_friend' user.username data.id %}">
                                    <div class="to-do-list-delete-button" data-id="{{data.id}}">Delete</div>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}       